"use client";

import { useEffect, useState } from "react";
import { OrbisDemo } from "@/components/orbis-demo";

export default function Home() {
  const [gameStarted, setGameStarted] = useState(false);
    const [seconds, setSeconds] = useState(599);
      const [choice, setChoice] = useState("");

        useEffect(() => {
            if (!gameStarted) return;

                const timer = setInterval(() => {
                      setSeconds((current) => (current > 0 ? current - 1 : 0));
                          }, 1000);

                              return () => clearInterval(timer);
                                }, [gameStarted]);

                                  const minutes = Math.floor(seconds / 60);
                                    const remainingSeconds = seconds % 60;

                                      const chooseAction = (action: string) => {
                                          setChoice(action);
                                            };

                                              if (!gameStarted) {
                                                  return (
                                                        <main>
                                                                <header>
                                                                          <h1>ZERO HOUR: 10:00</h1>

                                                                                    <p>
                                                                                                You wake up alone in an underground facility.
                                                                                                            Something has escaped.
                                                                                                                      </p>

                                                                                                                                <p>
                                                                                                                                            When the timer reaches zero, whatever is outside
                                                                                                                                                        will come inside.
                                                                                                                                                                  </p>

                                                                                                                                                                            <button
                                                                                                                                                                                        type="button"
                                                                                                                                                                                                    onClick={() => setGameStarted(true)}
                                                                                                                                                                                                              >
                                                                                                                                                                                                                          START GAME
                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                            </header>

                                                                                                                                                                                                                                                    <OrbisDemo />
                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                      <main>
                                                                                                                                                                                                                                                                            <header>
                                                                                                                                                                                                                                                                                    <h1>ZERO HOUR</h1>

                                                                                                                                                                                                                                                                                            <h2>
                                                                                                                                                                                                                                                                                                      {String(minutes).padStart(2, "0")}:
                                                                                                                                                                                                                                                                                                                {String(remainingSeconds).padStart(2, "0")}
                                                                                                                                                                                                                                                                                                                        </h2>

                                                                                                                                                                                                                                                                                                                                <p>
                                                                                                                                                                                                                                                                                                                                          Emergency lights flicker overhead.
                                                                                                                                                                                                                                                                                                                                                    A locked metal door stands ahead.
                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                                                                                                                                              <strong>UNKNOWN VOICE:</strong>
                                                                                                                                                                                                                                                                                                                                                                                        <br />
                                                                                                                                                                                                                                                                                                                                                                                                  "When the timer reaches zero, whatever is outside
                                                                                                                                                                                                                                                                                                                                                                                                            will come inside."
                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                          </header>

                                                                                                                                                                                                                                                                                                                                                                                                                                <section>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2>WHAT DO YOU DO?</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={() => chooseAction("SEARCH THE COMPUTER")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      SEARCH THE COMPUTER
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={() => chooseAction("TRY THE DOOR")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            TRY THE DOOR
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => chooseAction("ENTER THE VENT")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ENTER THE VENT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {choice && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        You chose: <strong>{choice}</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <OrbisDemo />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                        